FROM ubuntu

COPY . /app
WORKDIR /app

RUN set -eu \
    && apt-get update && apt-get install -y tzdata && \
    python3.9 \
    python3-pip \
    python3-venv \
    && pip install --no-cache-dir -r requirements.txt \
    && rm -rf /var/lib/apt/lists/*
